### ISSUE TITLE
Licence choice

### ISSUE THREAD

**Issue by drwlrsn** [BridgeCityBicycleCoop/workstand#1]
So we should probably pick a licence for this thing.
I am partial to the [MIT](https://opensource.org/licenses/MIT) and [BSD 2-Clause](https://opensource.org/licenses/BSD-2-Clause). This most likely because I am lazy and I don't like reading long licences.

@FeXd thoughts?

**Comment by FeXd** [comment]
I am fine with either.

**Comment by drwlrsn** [comment]
Can we have the copyright holder be the Bridge City Bicycle Co-op?

**Comment by FeXd** [comment]
Hmm I don't see why not.

**Comment by drwlrsn** [comment]
@FeXd Okay perfect. I don't want to make any assumptions just in case it's not something that the organization would want.
