### ISSUE TITLE
Name

### ISSUE THREAD

**Issue by drwlrsn** [BridgeCityBicycleCoop/workstand#2]
I picked a name. It's pretty decent. A URL exists for it and there is no project on GH with the same name.

I am still open to suggestions tho. I was hoping for some sort of animal pun like Velociraptor so we could get a cool logo. Pinging @FeXd

**Comment by FeXd** [comment]
I love the name; altho I do agree animal puns are fun. But workstand is great!

**Comment by drwlrsn** [comment]
Great. I like it too. I was just hoping you would be more creative than me.

**Comment by drwlrsn** [comment]
Seems like everyone loves Workstand
