### ISSUE TITLE
New member process

### ISSUE THREAD

**Issue by drwlrsn** [BridgeCityBicycleCoop/workstand#3]
@FeXd, I am trying to nail down how a new membership would be created. Right now I have three concepts that work together to create a full membership: `registration.models.Member`, `core.models.Membership`, and `core.models.Payment`.
- `Member` is responsible for the personal details and acknowledgements.
- `Membership` keeps track of the status of the member. E.g. the date the membership was created, when it expires, etc.
- `Payment` assigned to membership to determine how it was paid for.

My gut feeling for creating a new member would be to create a new `Member` and automatically create and add to `Member` a `Membership`. This `Membership` instance would have `payment = None` and be considered unpaid. After saving both, we could redirect to a page with payment options and maybe dispatch an email with the payment options as well.

Payment would still have to be manually assigned, but in the future we can enhance this to allow for the automatic buying and renewal of memberships.

**Comment by FeXd** [comment]
This sounds fine to me under the assumption that everyone being created wants to be a Member. For people that stop by the shop for either a visit or to donate bicycles, would we still create a new member and just never fill in payment? I suppose that we could also not create them and just have a way to sign-in people for ad-hoc visits that aren't in the system?

**Comment by drwlrsn** [comment]
> I  suppose that we could also not create them and just have a way to sign-in people for ad-hoc visits that aren't in the system?

That's a good point. We probably want to make it as easy as possible to sign someone in as a visitor if they don't have an _account_ (or whatever we are calling it). I should probably streamline that form so it just gets the bare minimum deets and then do all the acknowledgements, etc., with creating a membership.
