### ISSUE TITLE
Enhancement:  provide initial data

### ISSUE THREAD

**Issue by fspc** [BridgeCityBicycleCoop/workstand#69]
It would really help draw more attention to this project if there was some initial data to quickly spin up a working demo or development instance.  Normally this is done with initial data either as a fixture or sql.    Back on February 22, 2017 you said,

> Some dev data is defs on my todo list. I have a fairly long list at the moment tho. I am trying to get the bicycle tracking portion done before spring hits...

I think you are beyond that point now, so I am holding you to your todo list, todo this sooner, rather than later!

**Comment by drwlrsn** [comment]
Hey @fspc, I just opened a [PR](https://github.com/BridgeCityBicycleCoop/workstand/pull/70). I have updated the README on that branch to reflect the new install process. Can you have a look and see how that works for ya?

**Comment by fspc** [comment]
It works!   I didn't test out the docker-machine part, but rather I am using jrcs/letsencrypt-nginx-proxy-companion so it is currently up at https://workstand.bikelover.org.  All I had to do was change ALLOWED_HOSTS in production.py, and it is good to go.

**Comment by drwlrsn** [comment]
Glad to hear it! Yah the docker-machine stuff is just for local development. I had to run webpack as a separate docker service for some reason, but once the JS is built it is all just served from the **Workstand** service.
