### ISSUE TITLE
docker-compose.prod.yml - workstand.env missing

### ISSUE THREAD

**Issue by fspc** [BridgeCityBicycleCoop/workstand#71]
workstand.env is missing in the root

When running 

`docker-compose  -f docker-compose.yml -f docker-compose.prod.yml build`

`ERROR: Couldn't find env file: workstand.env`

**Comment by drwlrsn** [comment]
Oh shoot... yah I use that to inject:
1. `DJANGO_SECRET_KEY`
2. `MAILCHIMP_API_KEY`

And some stuff I don't and probably should...
*Task*
