### ISSUE TITLE
static content not being served when using production was (Add https to webpack)

### ISSUE THREAD

**Issue by fspc** [BridgeCityBicycleCoop/workstand#72]
Add https to webpack-dev-server or ensure workstand is serving those assets.

In  issue #69 you note:

```
- Mixed Content: The page at 'https://workstand.bikelover.org/members/' was loaded over HTTPS, but requested an insecure script 'http://192.168.99.100:3000/assets/bundles/members-07458b6f6b11b22dd314.js'. This request has been blocked; the content must be served over HTTPS.
- Mixed Content: The page at 'https://workstand.bikelover.org/members/' was loaded over HTTPS, but requested an insecure script 'http://192.168.99.100:3000/assets/bundles/babelPolyfill-07458b6f6b11b22dd314.js'. This request has been blocked; the content must be served over HTTPS.
```
Those assets are not being accessed simply because they are not being served from a secure server.

**Comment by drwlrsn** [comment]
The webpack service is only meant for development not production. I was following the one process per container idea of Docker, so it ended up in it's own service. For production, the JS is compiled during the build step of the `workstand` service container and served from it.

**Comment by fspc** [comment]
However, I am getting strange results when using docker-compose.prod.yml.  Please take a look at https://workstand.bikelover.org

**Comment by fspc** [comment]
I think I know what is causing the issue.

**Comment by drwlrsn** [comment]
Running in production is kinda outside the scope of quickstart... Have a look at the [nginx config](https://github.com/BridgeCityBicycleCoop/workstand/blob/master/docker/nginx/conf/nginx-site.conf#L370). Running the project with _docker-compose.prod.yml_ using `docker-compose` should be fairly straightforward after changing some of the hardcoded domain name settings in the _nginx-site.config_ and _production.py_

**Comment by fspc** [comment]
I am not using the nginx provided by prod.

**Comment by drwlrsn** [comment]
You'll need to serve the static files somehow. If you configured a webserver to direct requests to the you'll need to configure it serve those static assets. A shared volume is probably the easiest way to accomplish this.

**Comment by fspc** [comment]
Can gunicorn serve those static assets?

**Comment by drwlrsn** [comment]
I don't believe so. It is an application server not a webserver. See https://serverfault.com/questions/331256/why-do-i-need-nginx-and-something-like-gunicorn

**Comment by fspc** [comment]
Simple enough, that will just involve setting up a custom nginx configuration in nginx-proxy to serve the static content.

**Comment by drwlrsn** [comment]
Yah that's kinda up to you if want. The project includes a nginx reverse proxy service. You would have to disable HTTPS until you could get the certs into the container... but it's pretty close to what you need.
