### ISSUE TITLE
Tables in mobile view

### ISSUE THREAD

**Issue by drwlrsn** [BridgeCityBicycleCoop/workstand#77]
Better tables in mobile view. Look at material-ui v1.

**Comment by drwlrsn** [comment]
Upgrading to v1 will fix this.

**Comment by FeXd** [comment]
Example of a current mobile table:

![image](https://user-images.githubusercontent.com/553767/38771833-56d7b2cc-3fe7-11e8-8fbe-f3205085a783.png)
