### ISSUE TITLE
New member form displays incorrect error message for name

### ISSUE THREAD

**Issue by rowan-maclachlan** [BridgeCityBicycleCoop/workstand#82]
![screen shot 2018-04-29 at 11 36 23](https://user-images.githubusercontent.com/7827949/39409297-b36e76cc-4ba1-11e8-946f-017b85bc2f8c.png)

'First name' and 'Last name' display an error message about user entries being too long even when there is nothing entered.  The form should display that the user entry is too short (and minimum length perhaps) up until the point that requirement is satisfied.  It should display "too long" (and maximum length) until the point *that* requirement is satisfied.  Maybe it should do lots of other stuff too :)

**Comment by nemesis1346** [comment]
should it be done with regular expressions too? which minimum length?

**Comment by drwlrsn** [comment]
Hey @nemesis1346 it looks like we are rendering the template based on form class:
https://github.com/BridgeCityBicycleCoop/workstand/blob/d203111eecc0d622eb5c48ba2a4d9a81d89fd94b/bikeshop_project/registration/templates/member_form.html#L107-L115

And rendering some error classes based on the instance properties
https://github.com/BridgeCityBicycleCoop/workstand/blob/d203111eecc0d622eb5c48ba2a4d9a81d89fd94b/bikeshop_project/registration/forms.py#L6-L27

And to be honest, this logic kinda seems flawed:
https://github.com/BridgeCityBicycleCoop/workstand/blob/d203111eecc0d622eb5c48ba2a4d9a81d89fd94b/bikeshop_project/registration/templates/member_form.html#L110-L114
