### ISSUE TITLE
Request: Add More Purposes

### ISSUE THREAD

**Issue by FeXd** [BridgeCityBicycleCoop/workstand#86]
Some users are visiting for different reasons we would like to track. Add these options:

- parts
- buy bike
- tour / visit

**Comment by nemesis1346** [comment]
Is this issue still open? In which page does this have to be fixed?

**Comment by drwlrsn** [comment]
Hey Marco, you can find where they are defined in Django model here:
https://github.com/BridgeCityBicycleCoop/workstand/blob/d203111eecc0d622eb5c48ba2a4d9a81d89fd94b/bikeshop_project/core/models.py#L50-L67

And they are surfaced to front end here:
https://github.com/BridgeCityBicycleCoop/workstand/blob/d203111eecc0d622eb5c48ba2a4d9a81d89fd94b/bikeshop_project/assets/js/components/Purpose.jsx#L5-L18

**Comment by nemesis1346** [comment]
I couldnt find those options in the Front End in the New Member Form? 

I just found a similar checklist in the following file:

bikeshop_project/registration/models.py

Is that what this is about? I cannot yet find the other interface in workstand/bikeshop_project/assets/js/components/Purpose.jsx

**Comment by nemesis1346** [comment]
Links:

[bikeshop_project/registration/models.py](url)
[workstand/bikeshop_project/assets/js/components/Purpose.jsx](url)

**Comment by nemesis1346** [comment]
is this the page we are trying to fix? This is my fix. 
![Screenshot from 2019-06-08 10-55-49](https://user-images.githubusercontent.com/16295160/59150136-04ed9400-89dc-11e9-849e-c89681533073.png)

**Comment by FeXd** [comment]
The New Contact form **involvement** second is not the place for this.

Instead, is should be on the SignIn page:
![image](https://user-images.githubusercontent.com/553767/59391175-c4ba4880-8d30-11e9-8091-861a153dc50b.png)

**Comment by nemesis1346** [comment]
So it is working already?

**Comment by FeXd** [comment]
Yes looks like #89 fixes this.
